-- 1. 이름이 없는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME is NULL ORDER BY ANIMAL_ID ASC;

-- 2. 이름이 있는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME is not Null ORDER BY ANIMAL_ID ASC;

-- 3. NULL 처리하기
SELECT ANIMAL_TYPE, case when NAME is null then 'No name' else NAME end AS NAME, SEX_UPON_INTAKE FROM ANIMAL_INS ORDER BY ANIMAL_ID ASC